dist: trusty
language: node_js
cache: npm
sudo: required
env:
  - TEST_SUITE="test"
  - TEST_SUITE="test:integration"
  - TEST_SUITE="test:tools"
  - TEST_SUITE="build-package"
branches:
  only:
  - master
  - develop
  - /^feature\/.*/
  - /^release-.*/
  - /^hotfix-.*/
notifications:
  email:
    recipients:
      - ci.report@ost.com
    on_success: always
    on_failure: always
node_js:
  - "8"
before_script:
  - ./tools/runGanacheCli.sh </dev/null 1>/dev/null 2>&1 &
  - npm run compile:ts
script:
  - npm run ${TEST_SUITE}
after_script:
  - kill $(ps aux | grep 'ganache-cli' | awk '{print $2}')
