dist: trusty
language: node_js
cache: npm
sudo: required
env:
  - TEST_SUITE="test:deployment_tool",
  - TEST_SUITE="test:fuzzy_proof_generator",
  - TEST_SUITE="test:integration",
  - TEST_SUITE="test:unit",
  - TEST_SUITE="build:package"
branches:
  only:
  - master
  - develop
  - /^feature\/.*/
  - /^release-.*/
  - /^hotfix-.*/
notifications:
  email:
    recipients:
      - ci.report@ost.com
    on_success: always
    on_failure: always
node_js:
  - "8"
before_script:
  - npm run compile
  - npm run build:package
  - npm run generate:interacts
  - npm run compile:ts
  - ./tools/runGanacheCli.sh </dev/null 1>/dev/null 2>&1 &
script:
  - npm run ${TEST_SUITE}
after_script:
  - kill $(ps aux | grep 'ganache-cli' | awk '{print $2}')
